### ISSUE TITLE
can't working with Qt::AA_UseOpenGLES

### ISSUE THREAD

**Issue by ZhouYing-bit** [MasterAler/SampleYUVRenderer#8]
Hi, bro, first I want to thank you sharing;

I have a problem,  player can't display correctly when I set     **qApp->setAttribute(Qt::AA_UseOpenGLES);** 
as follows:

``` 
int main(int argc, char *argv[])
{
    qApp->setAttribute(Qt::AA_UseOpenGLES);

    QApplication a(argc, argv);
    TestWidget w;
    w.show();
    w.readAllSampleFile();

    return a.exec();
}

```
![image](https://user-images.githubusercontent.com/13702789/136181690-8a36488b-e604-438f-9ac3-70c7ab9f8803.png)

Look forward to your reply!

**Comment by MasterAler** [comment]
@ZhouYing-bit 
Wa-wa-wait a minute! You are _not_ trying to launch it on Windows desktop, are you?
Because Qt uses [ANGLE](https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL) there, a thingie that relies on DirectX and becomes a bridge between it and your actual OpenGL code. That means in the case you find yourself very far from actual OpenGL ES 2.0 , something may break.

So. what are you trying to achieve and what's your platform?

**Comment by MasterAler** [comment]
@ZhouYing-bit 
Okay, I assume that the problem has been solved somehow, so I'm closing the current issue due to it probably becoming outdated.
Feel free to share your solution or any more details if any happen to appear.
